import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {PRESET_SCENARIOS,type AcdocaLine} from '../src/types';
import {computeMTO,generateStepEntries,STEP_DEFINITIONS,computeStockEState,computeSalesOrderCostCard,resolveRouting,formatVND} from '../src/utils/calculator';
import {canonicalBomTree,planGroups,dashboardView,settlementView,displayedBomInputs,postedCostCard,journalDescription} from '../src/presentation/finance';
import {SpecialStockPanel} from '../src/components/SpecialStockPanel';
import {StepCard} from '../src/components/StepCard';
import {SetupScreen} from '../src/components/SetupScreen';
import {selectMarginAnalysis} from '../src/utils/acdoca';
import {BOMVisualizer} from '../src/components/BOMVisualizer';
const expected=JSON.parse(readFileSync(new URL('./a0_expected.json',import.meta.url),'utf8'));
assert.equal(expected.length,54);
let count=0;
for(const e of expected){
  const preset=PRESET_SCENARIOS.find(p=>p.id===e.src)!;
  const p={...preset.params,stockType:e.stock,actualVariancePercent:e.pct,deliveredQuantity:Math.round(preset.params.orderQuantity*e.ratio)};
  const c=computeMTO(p),t:AcdocaLine[]=[];
  for(let st=1;st<=7;st++)t.push(...generateStepEntries(st,p,c,0,0,null).acdoca);
  const view=dashboardView(p,c,t),settle=settlementView(p,c,t,true);
  const master=displayedBomInputs(p,c);
  assert.equal(master.reduce((sum,b)=>sum+Math.round(p.orderQuantity/1000*b.qtyPer1000*(1+b.scrapRatePercent/100)*b.unitPrice),0),c.materialCost,'master grid same material value as calculator');
  assert.deepEqual(master.map(b=>b.name),c.bomItemBreakdowns!.map(b=>b.name));
  const card=postedCostCard(computeSalesOrderCostCard(7,p,c),p,c,t);
  assert.equal(card.recognizedRevenue,e.revenue_recognized);assert.equal(card.actualGrossProfit,e.gp911_credit);
  assert.equal(card.recognizedCOGS,view.cogs);assert.equal(card.totalAccumulatedCost,c.actualCostBeforeRework);
  assert.ok(selectMarginAnalysis(t,card.actualGrossProfit).matchesOrderCard,'card must match Margin Analysis');
  const setup=renderToStaticMarkup(<SetupScreen params={p} computed={c} onChangeParams={()=>{}} onStartSimulation={()=>{}}/>);
  for(const b of master)assert.ok(setup.includes(`value="${b.itemCode}"`),'rendered editor must use active material');
  assert.ok(setup.includes(`value="${resolveRouting(p).laborHourlyRate}"`),'rendered routing rates');
  assert.equal(view.revenue,e.revenue_recognized);
  assert.equal(view.grossProfit,e.gp911_credit,'profit must equal independent oracle after closing');
  assert.equal(view.cogs,e.revenue_recognized-e.gp911_credit);
  assert.equal(settle.wip,e.wip154_dr_minus_cr,'narrative WIP must match independent oracle');
  assert.equal(view.breakdown.reduce((s,i)=>s+i.value,0),view.cogs,'signed bridge must match posted COGS');
  if(view.cogs>0)assert.ok(Math.abs(view.breakdown.reduce((s,i)=>s+i.value/view.cogs*100,0)-100)<1e-9,'percent sum100');
  if(e.pct<0 && e.ratio>0)assert.ok(view.breakdown.at(-1)!.value<0,'favorable delta must retain minus sign');
  const groups=planGroups(p,c),tree=canonicalBomTree(p,c);
  assert.equal(groups.reduce((s,g)=>s+g.cost,0),c.plannedCost);
  assert.equal(tree.children!.reduce((s,g)=>s+g.totalCost,0),c.plannedCost);
  for(const g of tree.children!)assert.equal(g.children!.reduce((s,i)=>s+i.totalCost,0),g.totalCost,'BOM child sum');
  assert.deepEqual(tree.children![0].children!.map(i=>i.description),c.bomItemBreakdowns!.map(i=>i.name));
  const empty=dashboardView(p,c,[]);assert.equal(empty.cogs,0);assert.equal(empty.revenue,0);
  const stock=computeStockEState(2,p,c,null,false);
  const html=renderToStaticMarkup(<SpecialStockPanel stockState={stock} params={p} lastExecutedStep={2}/>);
  assert.match(html,/Đã dự trù theo MRP/);assert.doesNotMatch(html,/Đã xuất kho đưa vào/);
  const noop=()=>{};
  const stepHtml=renderToStaticMarkup(<StepCard step={STEP_DEFINITIONS.find(s=>s.id===7)!} isActive isExecuted
    stepState={{isExecuted:true,qmDecision:null,qmResolutionMethod:null,qmReworkHandled:false,qmReworkCost:0,qmScrapCost:0,actualVariancePercent:p.actualVariancePercent,entries:[],acdocaLines:[]}}
    params={p} computed={c} acdocaTable={t} onExecute={noop} onQMDecision={noop} onHandleQMResolution={noop} onExplainStep={noop} canExecute/>);
  assert.doesNotMatch(stepHtml,/tất toán tài khoản 154 về 0/);
  const bill=generateStepEntries(6,p,c,0,0,null).entries.find(entry=>entry.creditAccount==='511');
  if(bill)assert.ok(journalDescription(bill,p).includes(p.deliveredQuantity.toLocaleString('vi-VN')+' cái'),'billing narrative uses delivered quantity');
  assert.ok(stepHtml.includes(formatVND(settle.wip)),'rendered narrative must show WIP');
  if(e.stock==='Non-valuated')assert.ok(stepHtml.includes(formatVND(settle.settled)),'rendered settlement share');
  const bomHtml=renderToStaticMarkup(<BOMVisualizer params={p} computed={c}/>);
  assert.ok(bomHtml.includes(formatVND(c.materialCost)),'rendered BOM must show canonical material total');
  count++;
}
console.log(`PASS UI finance ${count}/54 oracle cases; posted profit/WIP; signed bridge; canonical BOM; rendered inventory/narratives.`);
